CREATE DATABASE POCKET_WORLDS_TEST;
USE POCKET_WORLDS_TEST;

CREATE TABLE PW_MAP_TYPE_LEVELS (
     PW_MAP_TYPE_LEVEL_ID INT NOT NULL UNIQUE AUTO_INCREMENT,
     PW_MAP_TYPE_LEVEL_KEY INT NOT NULL UNIQUE,
     PW_MAP_TYPE_LEVEL_NAME CHAR(30) NOT NULL,
     PRIMARY KEY (PW_MAP_TYPE_LEVEL_ID)
);

CREATE TABLE PW_MAP_TYPES (
     PW_MAP_TYPE_ID INT NOT NULL UNIQUE AUTO_INCREMENT,
     PW_MAP_TYPE_KEY INT NOT NULL UNIQUE,
	 PW_MAP_TYPE_LEVEL_KEY INT NOT NULL,
     PW_MAP_TYPE_NAME CHAR(30) NOT NULL,
     PRIMARY KEY (PW_MAP_TYPE_ID),
	 FOREIGN KEY (PW_MAP_TYPE_LEVEL_KEY) REFERENCES PW_MAP_TYPE_LEVELS(PW_MAP_TYPE_LEVEL_KEY)
		ON DELETE RESTRICT
);

CREATE TABLE PW_MAP_ELEM_TYPES (
     PW_MAP_ELEM_TYPE_ID INT NOT NULL UNIQUE AUTO_INCREMENT,
     PW_MAP_ELEM_TYPE_KEY INT NOT NULL UNIQUE,
     PW_MAP_ELEM_TYPE_NAME CHAR(30) NOT NULL,
     PRIMARY KEY (PW_MAP_ELEM_TYPE_ID)
);

CREATE TABLE PW_MAPS (
     PW_MAP_ID INT NOT NULL AUTO_INCREMENT,
     PW_MAP_TYPE_KEY INT NOT NULL,
     PW_MAP_NAME CHAR(30) NOT NULL,
     PW_MAP_SIZE_X INT NOT NULL,
     PW_MAP_SIZE_Y INT NOT NULL,
	 PW_MAP_PARENT_ID INT,
     PRIMARY KEY (PW_MAP_ID),
	 FOREIGN KEY (PW_MAP_TYPE_KEY) REFERENCES PW_MAP_TYPES(PW_MAP_TYPE_KEY)
		ON DELETE RESTRICT,
	 FOREIGN KEY (PW_MAP_PARENT_ID) REFERENCES PW_MAPS(PW_MAP_ID)
		ON DELETE RESTRICT
);

CREATE TABLE PW_MAPS_ELEMENTS (
	 PW_MAP_ID INT NOT NULL,
     X_POSITION INT NOT NULL,
     Y_POSITION INT NOT NULL,
     PW_MAP_ELEM_TYPE_ID INT NOT NULL,
     PRIMARY KEY (PW_MAP_ID,X_POSITION,Y_POSITION),
	 FOREIGN KEY (PW_MAP_ID) REFERENCES PW_MAPS(PW_MAP_ID)
		ON DELETE RESTRICT,
	 FOREIGN KEY (PW_MAP_ELEM_TYPE_ID) REFERENCES PW_MAP_ELEM_TYPES(PW_MAP_ELEM_TYPE_ID)
		ON DELETE RESTRICT
);

