-- DROP DATABASE POCKET_WORLDS_TEST;

DROP PROCEDURE IF EXISTS CREATE_MAP;
DROP TABLE IF EXISTS PW_MAPS_ELEMENTS;
DROP TABLE IF EXISTS PW_MAPS;
DROP TABLE IF EXISTS PW_MAP_ELEM_TYPES;
DROP TABLE IF EXISTS PW_MAP_TYPES;
DROP TABLE IF EXISTS PW_MAP_TYPE_LEVELS;
